[package]
name = "amethyst"
authors = ["Amethyst Core"]
description = "CLI Tool to interact with the Amethyst core in your terminal"
repository = "https://github.com/amethyst-core/cli"
readme = "README.md"
keywords = ["cli", "amethyst", "minecraft", "server", "management"]

version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
serde = { version = "1.0.203", features = ["derive"] }
dirs = "5.0.1"
reqwest = { version = "0.12.4", features = ["blocking", "json", "stream"] }
semver = { version = "1.0.23", features = ["serde"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
serde_json = "1.0.117"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
exitcode = "1.1.2"
indicatif = "0.17.8"
futures = "0.3.30"
